name: do it

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: { }
  repository_dispatch:
    types: [make_index]

jobs:
  pack:
    runs-on: ubuntu-latest
    env:
      SYNAPSE_CONFIG: ${{ secrets.SYNAPSE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tasks
        run: |
          ./gradlew runPack
