name: do pack

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs: { }
  repository_dispatch:
    types: [make_index]

jobs:
  pack:
    runs-on: ubuntu-latest
    env:
      SYNAPSE_CONFIG: ${{ secrets.SYNAPSE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
      - name: Index
        run: ./gradlew runIndex
      - name: Pack
        run: ./gradlew runPack
